blog/urls.py
# _*_ encoding:utf-8 _*_
__author__ = "ludada"
__date__ = "2018/9/25 19:29"
from django.urls import path
from blog.views import blog_detail, blog_type_list, blog_list, blog_with_dates
app_name ='[blog]'
urlpatterns = [
    path('blog_list', blog_list, name='blog_list'),
    path('<int:blog_id>', blog_detail, name='blog_detail'),
    path('blog_type_list/<int:blog_type_id>',blog_type_list, name='blog_type_list' ),
    path('date/<int:year>/<int:month>', blog_with_dates, name='blog_dates'),
    ]

comment/urls.py
# _*_ encoding:utf-8 _*_
__author__ = "ludada"
__date__ = "2018/9/28 21:12"
from django.urls import path
from . import views

app_name ='[comment]'
urlpatterns = [
    path('update_comment', views.update_comment, name='update_comment')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from django.conf import settings
from django.conf.urls.static import static
from mysite.views import userlogin, register, active

from .views import home
urlpatterns = [
    path('', home, name='home'),
    path('login/',userlogin, name='login'),
    path('register/',register, name='register'),
    re_path('active/(?P<active_code>.*)/', active, name='user_active'),
    path('captcha/', include('captcha.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('comment/', include('comment.urls', namespace='comment'))
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
# _*_ encoding:utf-8 _*_

from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.contenttypes.models import ContentType
from read_record.models import ReadNum
from django.db.models.fields import exceptions

class BlogType(models.Model):
    type_name = models.CharField(max_length = 15)

    class Meta:
        verbose_name=u'博客类型'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.type_name


class Blog(models.Model):
    title = models.CharField(max_length=30)
    blog_type = models.ForeignKey(BlogType, on_delete=models.CASCADE)
    content = RichTextUploadingField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    createtime = models.DateTimeField(auto_now_add=True)
    last_update_time = models.DateTimeField(auto_now = True)

    class Meta:
        ordering = ['-createtime']
        verbose_name=u'博客'
        verbose_name_plural = verbose_name
    def get_read_num(self):
        ct = ContentType.objects.get_for_model(Blog)
        try:
            readnum = ReadNum.objects.get(content_type=ct, object_id=self.id)
            return readnum.read_num
        except exceptions.ObjectDoesNotExist:
            return 0


    def __str__(self):
        return "<Blog: %s>" % self.title

# class ReadNum(models.Model):
#     read_num = models.IntegerField(default=0, verbose_name=u'博客阅读数')
#     blog = models.OneToOneField(Blog, on_delete=models.CASCADE)
#

blog/views.py
test1 001
test2 002
test3 003
from django.shortcuts import render, get_object_or_404
from .models import Blog, BlogType
from read_record.models import ReadNum, ReadDetail
from pure_pagination import Paginator,  PageNotAnInteger
from django.db.models import Count
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone

def blog_list(request):
    context = {}
    context['blogs'] = Blog.objects.all()
    context['blog_types'] = BlogType.objects.annotate(blog_count=Count('blog'))
    blog_dates = Blog.objects.dates('createtime', 'year', order='DESC')
    blog_dates_counts = {}
    for blog_date in blog_dates:
        blog_count = Blog.objects.filter(createtime__year=blog_date.year).count()
        blog_dates_counts[blog_date] = blog_count

    context['blog_dates'] = blog_dates_counts
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1

    p = Paginator(context['blogs'], 3, request=request)

    context['page_of_blogs'] = p.page(page)
    return render(request,'blog_list.html', context)

def blog_detail(request, blog_id):
    context = {}
    blog = get_object_or_404(Blog, id=blog_id)
    context['blog'] = blog

    if not request.COOKIES.get('blog_%s_readed' % blog_id):
        ct = ContentType.objects.get_for_model(Blog)
        if ReadNum.objects.filter(content_type=ct, object_id=blog.id).count():
           readnum = ReadNum.objects.get(content_type=ct, object_id=blog.id)
        else:
            readnum = ReadNum(content_type=ct, object_id=blog.id)
        readnum.read_num +=1
        readnum.save()
        date = timezone.now().date()
        readDetail, created = ReadDetail.objects.get_or_create(content_type=ct, object_id=blog.id, date=date)
        readDetail.read_num +=1
        readDetail.save()
    context['blog'].save()
    context['previous_blog'] = Blog.objects.filter(createtime__gt=context['blog'].createtime).last()
    context['next_blog'] = Blog.objects.filter(createtime__lt=context['blog'].createtime).first()
    response = render(request,'blog_detail.html', context)
    response.set_cookie('blog_%s_readed' % blog_id, 'true')
    return response

def blog_type_list(request, blog_type_id):
    context = {}
    blog_type = get_object_or_404(BlogType, id=blog_type_id)
    context['blogs'] = Blog.objects.filter(blog_type=blog_type)
    context['blog_type'] = blog_type
    context['blog_types'] = BlogType.objects.all()
    blog_dates = Blog.objects.dates('createtime', 'year', order='DESC')
    blog_dates_counts = {}
    for blog_date in blog_dates:
        blog_count = Blog.objects.filter(createtime__year=blog_date.year).count()
        blog_dates_counts[blog_date] = blog_count

    context['blog_dates'] = blog_dates_counts
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1

    p = Paginator(context['blogs'], 3, request=request)

    context['page_of_blogs'] = p.page(page)
    return render(request,'blog_type_list.html', context)

def blog_with_dates(request, year, month):
    context = {}
    context['blogs'] = Blog.objects.filter(createtime__year=year)
    context['blog_types'] = BlogType.objects.all()
    blog_dates = Blog.objects.dates('createtime', 'year', order='DESC')
    blog_dates_counts = {}
    for blog_date in blog_dates:
        blog_count = Blog.objects.filter(createtime__year=blog_date.year).count()
        blog_dates_counts[blog_date] = blog_count

    context['blog_dates'] = blog_dates_counts
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1

    p = Paginator(context['blogs'], 3, request=request)

    context['page_of_blogs'] = p.page(page)
    return render(request,'blog_with_dates.html', context)


# Create your views here.

blog/templates/blog_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load comment_tags %}
{% block title %}{{ blog.title }}{% endblock %}
<div class="container">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            {% block content %}
                <h3>{{ blog.title }}</h3>
                <ul class="blog-message">
                    <li>作者：{{ blog.author }}</li>
                    <li>发表日期：{{ blog.createtime|date:"Y-m-d h:n:s" }}</li>
                    <li>分类：<a href="{% url 'blog:blog_type_list' blog.blog_type.id %}">{{ blog.blog_type }}</a></li>
                    <li>阅读（{{ blog.get_read_num }}）</li>
                    <li>评论：({% get_comment_count blog %})</li>
                </ul>
            <div class="blog-content-desc">{{ blog.content|safe }}</div>
                <div class="more-blog">
                  <p>上一篇：
                      {% if previous_blog %}
                      <a href="{% url 'blog:blog_detail' previous_blog.id %}">
                      {{ previous_blog.title }}
                      </a>
                      {% else %}
                      这是第一篇文章
                      {% endif %}
                  </p>
                  <p>下一篇：
                      {% if next_blog %}
                          <a href="{% url 'blog:blog_detail' next_blog.id %}">
                          {{ next_blog.title }}
                          </a>
                      {% else %}
                      这是最后一篇文章
                      {% endif %}
                  </p>
                </div>

        </div>
   </div>
 <div class="row">
            <div class="col-xs-10 col-xs-offset-1">
                 <div class="comment-area">
                    <h3 class="comment-area-title">提交评论</h3>
                    {% if user.is_authenticated %}
                         <form id="comment_form" action="{% url 'comment:update_comment' %}" method="POST" style="overflow:hidden">
                            <label>{{ user.username }}，欢迎评论~</label>
                         <div id="reply_content_container" style="display:none;">
                                <p id="reply_title">回复：</p>
                                <div id="reply_content"></div>
                         </div>
                            {% csrf_token %}
                         {% get_comment_form blog as comment_form %}
                            {% for field in comment_form %}
                                {{ field }}
                            {% endfor %}
                            <span id="comment_error" class="text-danger pull-left"></span>
                            <input type="submit" value="评论" class="btn btn-primary pull-right">
                        </form>
                    {% else %}
                       您尚未登录，登录之后方可评论~
                        <a class="btn btn-primary" href="{% url 'login' %}?from={{ request.get_full_path }}">登录</a>
                        <span>or</span>
                        <a class="btn btn-primary" href="{% url 'register' %}?from={{ request.get_full_path }}">注册</a>
                    {% endif %}
                </div>
                <div class="comment-area">
                    <h3 class="comment-area-title">评论列表</h3>
                      <div id="comment_list">
                          {% get_comment_list blog as comments %}
                          {% for comment in comments %}
                            <div id="root_{{ comment.id }}" class="comment">
                                <span>{{ comment.user.username }}</span>
                                <span>({{ comment.comment_time|date:"Y-m-d H:i:s" }})：</span>
                                <div id="comment_{{ comment.id }}">
                                    {{ comment.comment_text|safe }}
                                </div>
                                <a href="javascript:reply({{ comment.id }});">回复</a>


                                {% for reply in comment.root_comment.all %}
                                    <div class="reply">
                                        <span>{{ reply.user.username }}</span>
                                        <span>({{ reply.comment_time|date:"Y-m-d H:i:s" }})</span>
                                        <span>回复</span>
                                        <span>{{ reply.reply_to.username }}：</span>
                                        <div id="comment_{{ reply.id }}">
                                            {{ reply.comment_text|safe }}
                                        </div>
                                        <a href="javascript:reply({{ reply.id }});">回复</a>
                                    </div>
                                {% endfor %}
                            </div>
                        {% empty %}
                             <span id="no_comment">暂无评论</span>
                        {% endfor %}
                    </div>
                </div>
            </div>
   {% block custom_js %}
    <script type="text/javascript" src="{% static "js/jquery.12.4.min.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
     <script type="text/javascript">
         function reply(reply_comment_id) {
             $('#reply_comment_id').val(reply_comment_id);
               var html = $("#comment_" + reply_comment_id).html();
            $('#reply_content').html(html);
            $('#reply_content_container').show();
              $('html').animate({scrollTop: $('#comment_form').offset().top - 60}, 300, function(){
                CKEDITOR.instances['id_comment_text'].focus();
            });
        }
         function numFormat(num){
                return ('00' + num).substr(-2);
            }
         function timeFormat(timestamp){
            var datetime = new Date(timestamp * 1000);
            var year = datetime.getFullYear();
            var month = numFormat(datetime.getMonth() + 1);
            var day = numFormat(datetime.getDate());
            var hour = numFormat(datetime.getHours());
            var minute = numFormat(datetime.getMinutes());
            var second = numFormat(datetime.getSeconds());
            return year + '-' + month + '-' + day + ' ' + hour + ':' + minute + ':' + second;
        }
        $("#comment_form").submit(function(){
            // 判断是否为空
            $("#comment_error").text('');
            if(CKEDITOR.instances["id_comment_text"].document.getBody().getText().trim()==''){
                $("#comment_error").text('评论内容不能为空');
                return false;
            }
            // 更新数据到textarea
            CKEDITOR.instances['id_comment_text'].updateElement();
            // 异步提交
            $.ajax({
                url: "{% url 'comment:update_comment' %}",
                type: 'POST',
                data: $(this).serialize(),
                cache: false,
                success: function(data){
                    console.log(data);
                    if(data['status']=="SUCCESS"){
                         if($('#reply_comment_id').val()=='0'){
                            // 插入评论
                            var comment_html = '<div id="root_' + data['id'] + '" class="comment"><span>' + data['username'] + '</span><span> (' + timeFormat(data['comment_time']) + ')：</span><div id="comment_' + data['id'] + '">' + data['text'] + '</div><a href="javascript:reply(' + data['id'] + ');">回复</a></div>';
                            $("#comment_list").prepend(comment_html);
                        }else{
                            // 插入回复
                            var reply_html ='<div class="reply"><span>' + data['username'] + '</span><span> (' + timeFormat(data['comment_time']) + ')</span><span> 回复 </span><span>' + data['reply_to'] + '：</span><div id="comment_' + data['id'] + '">' + data['text'] + '</div><a href="javascript:reply(' + data['id'] + ');">回复</a></div>';
                            $("#root_" + data['root_id']).append(reply_html);
                        }
                        // 清空编辑框的内容
                        CKEDITOR.instances['id_comment_text'].setData('');
                          $('#reply_content_container').hide();
                          $('#reply_comment_id').val('0');
                          $('#no_comment').remove();
                    }else{
                        // 显示错误信息
                        $("#comment_error").text(data['message']);
                    }
                },
                error: function(xhr){
                    console.log(xhr);
                }
            });
            return false;
        });

    </script>
{% endblock %}
        </div>
</div>
    {% endblock %}
{% block active_blog_list %}active{% endblock %}

blog/templates/blog_list.html
{% extends 'base.html' %}
{% load comment_tags %}
{% block title %}博客列表{% endblock %}
 {% block blog_list_title %}博客列表(一共有{{ blogs|length }}篇博客){% endblock %}
 {% block content %}
    <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-md-8">
        <div class="panel panel-default">
          <div class="panel-heading">
              博客
             </div>
          <div class="panel-body">

              {% for blog in page_of_blogs.object_list %}
          <div class="blog">
                <a href="{% url 'blog:blog_detail' blog.id %}"> <h3>{{ blog.title }}</h3></a>
                <p class="blog-info"> <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                   <a href="{% url 'blog:blog_type_list' blog.blog_type.id %}"> {{ blog.blog_type.type_name }}</a>&nbsp;&nbsp;
                    <span class="glyphicon glyphicon-time" aria-hidden="true"></span>{{ blog.createtime|date:'Y-m-d' }}&nbsp;&nbsp;阅读({{ blog.get_read_num }})&nbsp;&nbsp;评论({% get_comment_count blog %})</p>
                <p>{{ blog.content|truncatechars:30 }}</p>
          </div>
              {% empty %}
                <p>--暂无博客，敬请期待--</p>
                 {% endfor %}
         </div>
          </div>
        </div>

      <div class="hidden-xs col-sm-4 col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading">博客分类</div>
          <div class="panel-body">
            <ul style="list-style-type: none;">
              {% for blog_type in blog_types %}
              <li><a href="{% url 'blog:blog_type_list' blog_type.id %}" >{{ blog_type.type_name }}({{ blog_type.blog_set.count }})</a></li>
              {% endfor %}
          </ul>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">日期归档</div>
          <div class="panel-body">
            <ul style="list-style-type: none;">
              {% for blog_date,blog_count in blog_dates.items %}
              <li><a href="{% url 'blog:blog_dates' blog_date.year blog_date.month %}">{{ blog_date|date:'Y年' }}({{ blog_count }})</a></li>
              {% endfor %}
          </ul>
          </div>
        </div>
      </div>
   </div>
    <div class="paginator">
    <ul class="pagination">
                            {% if page_of_blogs.has_previous %}
                                <li class="long"><a href="?{{ page_of_blogs.previous_page_number.querystring }}">上一页</a></li>
                            {% endif %}

                            {% for page in page_of_blogs.pages %}
                                {% if page %}
                                    {% ifequal page page_of_blogs.number %}
                                        <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                    {% else %}
                                        <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                                    {% endifequal %}
                                {% else %}
                                    <li class="none"><a href="">...</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if page_of_blogs.has_next %}
                                <li class="long"><a href="?{{ page_of_blogs.next_page_number.querystring }}">下一页</a></li>
                            {% endif %}
              </ul>
    </div>
</div>



{% endblock %}
{% block active_blog_list %}active{% endblock %}

blog/templates/blog_type_list.html
{% extends 'blog_list.html' %}
{% block title %}{{ blog_type }}{% endblock %}
{% block blog_list_title %}{{ blog_type.type_name }}(一共有{{ blogs|length }}篇博客){% endblock %}

blog/templates/blog_with_dates.html
{% extends 'blog_list.html' %}
{% block title %}1919{% endblock %}
{% block blog_list_title %}{{ blog_type.type_name }}(一共有{{ blogs|length }}篇博客){% endblock %}