blog/urls.py
# _*_ encoding:utf-8 _*_
__author__ = "ludada"
__date__ = "2018/9/25 19:29"
from django.urls import path
from blog.views import blog_detail, blog_type_list, blog_list, blog_with_dates
app_name ='[blog]'
urlpatterns = [
    path('blog_list', blog_list, name='blog_list'),
    path('<int:blog_id>', blog_detail, name='blog_detail'),
    path('blog_type_list/<int:blog_type_id>',blog_type_list, name='blog_type_list' ),
    path('date/<int:year>/<int:month>', blog_with_dates, name='blog_dates'),
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from django.conf import settings
from django.conf.urls.static import static
from mysite.views import userlogin, register, active

from .views import home
urlpatterns = [
    path('', home, name='home'),
    path('login/',userlogin, name='login'),
    path('register/',register, name='register'),
    re_path('active/(?P<active_code>.*)/', active, name='user_active'),
    path('captcha/', include('captcha.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('comment/', include('comment.urls', namespace='comment'))
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>激活失败</title>
</head>
<body>
<p>激活失败</p>
</body>
</html>

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
     <script type="text/javascript" src="{% static 'js/jquery.12.4.min.js' %}"></script>
    <meta charset="UTF-8">
    <title>{% block title %}博客列表{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
{% block custom_css %}{% endblock %}
{% block custom_js %}{% endblock %}
</head>
<body class="background">
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">个人博客网站</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="{% block active_home %}{% endblock %}"><a href="{% url 'home' %}">首页 <span class="sr-only">(current)</span></a></li>
        <li class="{% block active_blog_list %}{% endblock %}"><a href="{% url 'blog:blog_list' %}">博客</a></li>
      </ul>
    </div>
  </div>
</div>
    {% block content %}{% endblock %}
    {% block blog_category %}{% endblock %}
     {% block blog_dates %}{% endblock %}

</body>
</html>

templates/error.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    我的网站|错误
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    {{ message }}
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block title %}我的网站|首页{% endblock %}
{% block custom_js %}
<script src="http://cdn.hcharts.cn/highcharts/highcharts.js"></script>
{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
  <div class="col-md-3">
  <div class="panel panel-default">
  <div class="panel-heading">阅读排行榜</div>
  <div class="panel-body">
    <div>
    <h3>当天阅读榜</h3>
     {% for today_data in today_read_datas %}
        {{ today_data.content_object.title }}({{ today_data.read_num }})
    {% endfor %}
     </div>
       <div>
        <h3>作天阅读榜</h3>
        {% for yestoday_data in yestoday_read_datas %}
        {{ yestoday_data.content_object.title }}({{ yestoday_data.read_num }})
        {% endfor %}
    </div>
  </div>
</div>

  </div>
  <div class="col-md-9">
      <h3 class="home-content">欢迎访问我的网站，随便看</h3>
    <!-- 图表容器 DOM -->
    <div id="container"></div>
    <script>
        // 图表配置
        var options = {
            chart: { type: 'line' },
            title: { text: null },
            xAxis: {
                categories: {{ dates|safe }},   // x 轴分类
                tickmarkPlacement: 'on',
            },
            yAxis: {
                title: { text: null },
                labels:{ enabled: false },
                gridLineDashStyle: 'Dash',
            },
            series: [{                              // 数据列
                name: '阅读量',                     // 数据列名
                data: {{ read_nums }}               // 数据
            }],
            plotOptions: {
                line: {
                    dataLabels: {
                        enabled: true
                    }
                }
            },
            legend: { enabled: false },
            credits: { enabled: false },
        };
        // 图表初始化函数
        var chart = Highcharts.chart('container', options);
    </script>


  </div>
</div>
</div>
{% endblock %}




{% block active_home %}active{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    我的网站|登录
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">登录</h3>
                    </div>
                    <div class="panel-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in login_form %}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                <p class="text-danger">{{ field.errors.as_text }}</p>
                            {% endfor %}
                            <span class="pull-left text-danger">{{ login_form.non_field_errors }}</span>
                            <input type="submit" value="登录" class="btn btn-primary pull-right">
                        {% csrf_token %}
                        </form>
                    </div>
                </div>                
            </div>
        </div>
    </div>    
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    我的网站|注册
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
    <div class="containter">
        <div class="row">
            <div class="col-xs-4 col-xs-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">登录</h3>
                    </div>
                    <div class="panel-body">
                        <form action="" method="POST">
                             {% csrf_token %}
                            {% for field in reg_form %}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                <p class="text-danger">{{ field.errors.as_text }}</p>
                            {% endfor %}
                            <span class="pull-left text-danger">{{ reg_form.non_field_errors }}</span>
                            <input type="submit" value="注册" class="btn btn-primary pull-right">
                            <div>
                            </div>

                        </form>
                    </div>
                </div>                
            </div>
        </div>
    </div>    
{% endblock %}